---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Delete the template
    vmware_guest:
      hostname: <hostname>
      username: <username>
      password: <password>
      validate_certs: False
      name: testvm
      state: absent
      force: yes

