---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Delete the template
    vmware_guest:
      hostname: 192.168.1.225
      username: administrator@vsphere.zippyops.com
      password: 2!ppy0pS
      validate_certs: False
      name: testvm
      state: absent
      force: yes

