---
- name: Create a apache
  hosts: centos
  gather_facts: no
  tasks:
  - name: Allow Network Ports in Firewalld
    firewalld:
     port: 80/tcp
     state: enabled
     permanent: yes
     immediate: yes
  - name: install apache server
    yum: 
      name: httpd 
      state: latest
  - name: Starting and Enabling the required services
    service:
     name: httpd
     state: started
     enabled: yes
    
