---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: transfer ssh-key
    shell: sshpass -p "<password>" ssh-copy-id -o StrictHostKeyChecking=no root@192.168.1.55
